FROM arm32v7/ros:kinetic-perception

WORKDIR /opt/catkin_ws

RUN apt-get update && \
	apt-get install python-pip -yq && \
	pip install scipy && \
	apt-get clean && rm -rf /var/lib/apt/lists/*

COPY catkin_ws/src ./src
COPY catkin_ws/.catkin_workspace ./.catkin_workspace
COPY catkin_ws/test_data ./test_data

RUN . /opt/ros/kinetic/setup.sh && \
	catkin_make

COPY ./ros-entrypoint.sh .

CMD ["bash", "ros-entrypoint.sh", "roscore"]
