FROM arm32v7/ros:kinetic-perception

WORKDIR /opt/catkin_ws

COPY catkin_ws/src ./src
COPY catkin_ws/.catkin_workspace ./.catkin_workspace

RUN . /opt/ros/kinetic/setup.sh && \
	catkin_make

COPY ./ros-entrypoint.sh .

CMD ["bash", "ros-entrypoint.sh", "roscore"]
